name: CanvasTasks
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  googleapis: ^0.54.0
#  googleapis_auth: ^0.2.11+1
  #js: ^0.6.1
  google_apps: ^0.1.2
  http: ^0.12.0+4
  tuple: ^1.0.3
  html: ^0.14.0+3
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
